# Generated by Django 6.0.2 on 2026-03-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
