# Generated by Django 6.0.3 on 2026-03-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_booking_payment_id_booking_payment_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='coupon_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='package_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='wallet_amount_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
